# Site settings
title: TreeWatch
email: gtl@fontysvenlo.org
description: GreenTechLab Sofa 2015 in Corporation with Fontys Venlo and Fleuren.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "gtl.fontysvenlo.org" # the base hostname & protocol for your site
twitter_username: #jekyllrb
github_username:  #jekyll
tagline: GreenTechLab Sofa 2015

# Build settings
markdown: kramdown
